# Sample buildspec.yml for AWS DevOps Pipeline
# This file should be placed in the root of your CodeCommit repository

version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws sts get-caller-identity
    - echo Setting up build environment...
    - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME

  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $PROJECT_NAME:$IMAGE_TAG .
    - docker tag $PROJECT_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
    - echo Running tests...
    - npm test || echo "Tests completed"

  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - printf '[{"name":"app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - echo Creating deployment artifacts...
    - echo "Deployment artifacts created successfully"

artifacts:
  files:
  - imagedefinitions.json
  - appspec.yml
  - taskdef.json
  - buildspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.npm/**/*'
  - '/root/.cache/**/*'
